apiVersion: v1
kind: Service
metadata:
  name: hello-fargate
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: hello-fargate
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-fargate
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  selector:
    matchLabels:
      app: hello-fargate
  template:
    metadata:
      labels:
        app: hello-fargate
    spec:
      containers:
      - name: hello-fargate
        image: CONTAINER_IMAGE
        ports:
        - containerPort: 80